// StatBank Denmark Dashboard Controller

document.addEventListener("DOMContentLoaded", () => {
  const data = window.STATS_DATA;
  if (!data) {
    showError("Data not found. Please ensure data.js has been generated by running prefetch.py.");
    return;
  }

  // Retrieve sorted quarter keys (e.g. "2008K1", "2008K2"...)
  const qKeys = Object.keys(data).sort();
  if (qKeys.length === 0) {
    showError("No data available in data.js.");
    return;
  }

  // DOM Elements
  const slider = document.getElementById("yearSlider");
  const yearValueText = document.getElementById("yearValue");
  const ticksContainer = document.getElementById("sliderTicks");

  const valPopulation = document.getElementById("valPopulation");
  const changePopulation = document.getElementById("changePopulation");
  const valNetMigration = document.getElementById("valNetMigration");
  const changeNetMigration = document.getElementById("changeNetMigration");
  const valImmigrantShare = document.getElementById("valImmigrantShare");
  const changeImmigrantShare = document.getElementById("changeImmigrantShare");
  const valDescendantShare = document.getElementById("valDescendantShare");
  const changeDescendantShare = document.getElementById("changeDescendantShare");
  const otherCountriesPanel = document.getElementById("otherCountriesPanel");

  // Setup Slider limits dynamically based on indices (0 to N-1)
  slider.min = 0;
  slider.max = qKeys.length - 1;
  slider.step = 1;
  
  // Set default initial position to the latest available quarter
  const initialIndex = qKeys.length - 1;
  slider.value = initialIndex;
  
  const initialQKey = qKeys[initialIndex];
  yearValueText.textContent = data[initialQKey].label; // Displays MM-YYYY

  // Generate ticks under slider (spaced out visually)
  generateSliderTicks(qKeys, ticksContainer, slider);

  // Fixed maximum limit for x-axis scale on the Top 10 chart (as requested)
  const chartMax = 70000;

  // Chart instances
  let migrationChartInstance = null;
  let ancestryChartInstance = null;

  // Function to calculate Top 10 + Other metrics from STATS_DATA
  const getTopCountriesData = (qKey) => {
    const activeData = data[qKey].population;
    const countriesList = Object.entries(activeData.immigrant_countries)
      .map(([country, count]) => {
        // Map country names to shortened codes
        let displayName = country;
        if (country === "Bosnia and Herzegovina") displayName = "Bosnia";
        if (country === "United Kingdom") displayName = "UK";
        return { country: displayName, count };
      })
      .sort((a, b) => b.count - a.count);
    
    const top10 = countriesList.slice(0, 10);
    const top10Sum = top10.reduce((sum, item) => sum + item.count, 0);
    const otherCount = activeData.immigrants - top10Sum;
    const otherPct = (otherCount / activeData.immigrants * 100).toFixed(2);
    
    const labels = top10.map(item => item.country);
    const values = top10.map(item => item.count);
    
    return { labels, values, otherCount, otherPct };
  };

  // Initialize Dashboard
  initCharts(initialQKey);
  updateMetrics(initialQKey);
  updateOtherPanel(initialQKey);

  // Slider Event Listener
  slider.addEventListener("input", (e) => {
    const selectedIdx = parseInt(e.target.value, 10);
    const qKey = qKeys[selectedIdx];
    yearValueText.textContent = data[qKey].label;
    
    // Update active tick styling
    document.querySelectorAll(".tick-mark").forEach(tick => {
      const tickIdx = parseInt(tick.dataset.index, 10);
      const tickQKey = qKeys[tickIdx];
      const tickYear = tickQKey.substring(0, 4);
      const selectedYear = qKey.substring(0, 4);
      
      if (tickYear === selectedYear) {
        tick.classList.add("active");
      } else {
        tick.classList.remove("active");
      }
    });

    updateDashboard(qKey);
  });

  // Ticks click handlers
  ticksContainer.addEventListener("click", (e) => {
    if (e.target.classList.contains("tick-mark")) {
      const selectedIdx = parseInt(e.target.dataset.index, 10);
      slider.value = selectedIdx;
      const qKey = qKeys[selectedIdx];
      yearValueText.textContent = data[qKey].label;
      
      document.querySelectorAll(".tick-mark").forEach(tick => tick.classList.remove("active"));
      e.target.classList.add("active");
      
      updateDashboard(qKey);
    }
  });

  function updateDashboard(qKey) {
    updateMetrics(qKey);
    updateCharts(qKey);
    updateOtherPanel(qKey);
  }

  // Generate ticks under slider
  function generateSliderTicks(qKeysList, container, sliderInput) {
    container.innerHTML = "";
    qKeysList.forEach((qk, idx) => {
      const year = qk.substring(0, 4);
      const isQ1 = qk.endsWith('K1');
      if ((isQ1 && parseInt(year, 10) % 2 === 0) || idx === 0 || idx === qKeysList.length - 1) {
        const tick = document.createElement("span");
        tick.className = "tick-mark";
        if (idx === parseInt(sliderInput.value, 10)) {
          tick.className += " active";
        }
        tick.textContent = year;
        tick.dataset.index = idx;
        container.appendChild(tick);
      }
    });
  }

  // Helper to format numbers with commas
  function formatNum(n) {
    return new Intl.NumberFormat('en-US').format(n);
  }

  // Calculate and display metrics
  function updateMetrics(qKey) {
    const current = data[qKey];
    const currentIdx = qKeys.indexOf(qKey);
    const prevQKey = currentIdx > 0 ? qKeys[currentIdx - 1] : null;
    const prev = prevQKey ? data[prevQKey] : null;

    // 1. Total Population
    const pop = current.population.total;
    valPopulation.textContent = formatNum(pop);
    if (prev) {
      const popDiff = pop - prev.population.total;
      const popPct = (popDiff / prev.population.total * 100).toFixed(2);
      const isPositive = popDiff >= 0;
      setChangeElement(changePopulation, `${isPositive ? '+' : ''}${formatNum(popDiff)} (${isPositive ? '+' : ''}${popPct}%)`, isPositive);
    } else {
      setChangeNeutral(changePopulation);
    }

    // 2. Net Migration
    const immigrated = current.migration.immigrated;
    const emigrated = current.migration.emigrated;
    const net = immigrated - emigrated;
    valNetMigration.textContent = `${net >= 0 ? '+' : ''}${formatNum(net)}`;
    
    // Style net migration card if net is negative
    const netMigrationCard = document.getElementById("cardNetMigration");
    if (net < 0) {
      netMigrationCard.style.borderColor = "rgba(239, 68, 68, 0.25)";
    } else {
      netMigrationCard.style.borderColor = "var(--panel-border)";
    }

    if (prev) {
      const prevNet = prev.migration.immigrated - prev.migration.emigrated;
      const netDiff = net - prevNet;
      const isPositive = netDiff >= 0;
      setChangeElement(changeNetMigration, `${isPositive ? '↗' : '↘'} ${isPositive ? '+' : ''}${formatNum(netDiff)} vs prev quarter`, isPositive);
    } else {
      setChangeNeutral(changeNetMigration);
    }

    // 3. Immigrant Share
    const immTotal = current.population.immigrants;
    const immShare = (immTotal / pop * 100).toFixed(2);
    valImmigrantShare.textContent = `${immShare}%`;
    if (prev) {
      const prevPop = prev.population.total;
      const prevImmTotal = prev.population.immigrants;
      const prevImmShare = (prevImmTotal / prevPop * 100).toFixed(2);
      const shareDiff = (immShare - prevImmShare).toFixed(2);
      const isPositive = shareDiff >= 0;
      setChangeElement(changeImmigrantShare, `${isPositive ? '↑' : '↓'} ${isPositive ? '+' : ''}${shareDiff} pp`, isPositive);
    } else {
      setChangeNeutral(changeImmigrantShare);
    }

    // 4. Descendant Share
    const descTotal = current.population.descendants;
    const descShare = (descTotal / pop * 100).toFixed(2);
    valDescendantShare.textContent = `${descShare}%`;
    if (prev) {
      const prevPop = prev.population.total;
      const prevDescTotal = prev.population.descendants;
      const prevDescShare = (prevDescTotal / prevPop * 100).toFixed(2);
      const shareDiff = (descShare - prevDescShare).toFixed(2);
      const isPositive = shareDiff >= 0;
      setChangeElement(changeDescendantShare, `${isPositive ? '↑' : '↓'} ${isPositive ? '+' : ''}${shareDiff} pp`, isPositive);
    } else {
      setChangeNeutral(changeDescendantShare);
    }
  }

  function setChangeElement(el, text, isPositive) {
    el.className = `metric-change ${isPositive ? 'positive' : 'negative'}`;
    el.innerHTML = `<span class="change-icon">${isPositive ? '▲' : '▼'}</span> ${text}`;
  }

  function setChangeNeutral(el) {
    el.className = 'metric-change neutral';
    el.innerHTML = `<span class="change-icon">•</span> Baseline Quarter`;
  }

  // Update the visual other countries panel below the chart
  function updateOtherPanel(qKey) {
    const countryData = getTopCountriesData(qKey);
    otherCountriesPanel.innerHTML = `
      <div class="other-countries-label">Other</div>
      <div class="other-countries-bar-container">
        <div class="other-countries-bar-wrapper">
          <div class="other-countries-bar">
            <div class="scale-break"></div>
          </div>
          <span class="other-countries-value">${formatNum(countryData.otherCount)} <span class="other-countries-pct">(${countryData.otherPct}%)</span></span>
        </div>
      </div>
    `;
  }

  // Initialize charts using Chart.js
  function initCharts(activeQKey) {
    Chart.defaults.color = '#94a3b8';
    Chart.defaults.font.family = "'Outfit', sans-serif";

    // Chart 1: Migration Timeline (Quarterly)
    const migrationCtx = document.getElementById("migrationChart").getContext("2d");
    
    // Prepare timeline datasets
    const immigrationData = [];
    const emigrationData = [];
    // Convert K to Q for standard quarterly timeline display labels (e.g. 2008K1 -> Q1-08)
    const timelineLabels = qKeys.map(qk => {
      const yearShort = qk.substring(2, 4);
      const q = qk.substring(5, 7).replace('K', 'Q');
      return `${q}-${yearShort}`;
    });

    qKeys.forEach(qk => {
      immigrationData.push(data[qk].migration.immigrated);
      emigrationData.push(data[qk].migration.emigrated);
    });

    // Helper to generate dynamic colors for migration bars (highlighting selected quarter)
    const getMigrationColors = (selectedQKey, type) => {
      return qKeys.map(qk => {
        if (qk === selectedQKey) {
          return type === 'imm' ? '#10b981' : '#f97316';
        }
        return type === 'imm' ? 'rgba(16, 185, 129, 0.18)' : 'rgba(249, 115, 22, 0.18)';
      });
    };

    migrationChartInstance = new Chart(migrationCtx, {
      type: 'bar',
      data: {
        labels: timelineLabels,
        datasets: [
          {
            label: 'Immigrations',
            data: immigrationData,
            backgroundColor: getMigrationColors(activeQKey, 'imm'),
            borderRadius: 3,
            borderWidth: 0,
            barPercentage: 0.8,
            categoryPercentage: 0.85
          },
          {
            label: 'Emigrations',
            data: emigrationData,
            backgroundColor: getMigrationColors(activeQKey, 'emi'),
            borderRadius: 3,
            borderWidth: 0,
            barPercentage: 0.8,
            categoryPercentage: 0.85
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'top',
            labels: {
              boxWidth: 12,
              padding: 15,
              font: { size: 12, weight: 500 }
            }
          },
          tooltip: {
            backgroundColor: 'rgba(15, 23, 42, 0.95)',
            titleColor: '#f8fafc',
            bodyColor: '#e2e8f0',
            borderColor: 'rgba(255, 255, 255, 0.1)',
            borderWidth: 1,
            padding: 10,
            callbacks: {
              title: function(context) {
                const idx = context[0].dataIndex;
                const qKey = qKeys[idx];
                return `${data[qKey].label} (${qKey.replace('K', 'Q')})`;
              },
              label: function(context) {
                let label = context.dataset.label || '';
                if (label) {
                  label += ': ';
                }
                if (context.parsed.y !== null) {
                  label += formatNum(context.parsed.y);
                }
                return label;
              }
            }
          }
        },
        scales: {
          x: {
            grid: { display: false },
            ticks: {
              maxRotation: 0,
              autoSkip: true,
              maxTicksLimit: 12
            }
          },
          y: {
            grid: {
              color: 'rgba(255, 255, 255, 0.05)',
              drawTicks: false
            },
            ticks: {
              callback: function(value) {
                return value >= 1000 ? (value / 1000) + 'k' : value;
              }
            }
          }
        }
      }
    });

    // Chart 2: Immigrant Countries of Origin (Top 10 Only)
    const ancestryCtx = document.getElementById("ancestryChart").getContext("2d");
    const initialCountryData = getTopCountriesData(activeQKey);

    const ancestryColors = [
      '#6366f1', // Indigo
      '#3b82f6', // Blue
      '#06b6d4', // Cyan
      '#10b981', // Emerald
      '#84cc16', // Lime
      '#eab308', // Amber
      '#f97316', // Orange
      '#ef4444', // Red
      '#ec4899', // Pink
      '#d946ef'  // Fuchsia
    ];

    ancestryChartInstance = new Chart(ancestryCtx, {
      type: 'bar',
      data: {
        labels: initialCountryData.labels,
        datasets: [{
          data: initialCountryData.values,
          backgroundColor: ancestryColors,
          borderRadius: 4,
          borderWidth: 0,
          barThickness: 18
        }]
      },
      options: {
        indexAxis: 'y', // Horizontal bar chart
        responsive: true,
        maintainAspectRatio: false,
        layout: {
          padding: {
            right: 40
          }
        },
        plugins: {
          legend: { display: false },
          tooltip: {
            backgroundColor: 'rgba(15, 23, 42, 0.95)',
            titleColor: '#f8fafc',
            bodyColor: '#e2e8f0',
            borderColor: 'rgba(255, 255, 255, 0.1)',
            borderWidth: 1,
            padding: 10,
            callbacks: {
              label: function(context) {
                const value = context.parsed.x;
                const activeIdx = parseInt(slider.value, 10);
                const activeQKey = qKeys[activeIdx];
                const activeDataVal = data[activeQKey].population;
                const totalImmigrants = activeDataVal.immigrants;
                const totalPop = activeDataVal.total;
                
                const pctOfImmigrants = (value / totalImmigrants * 100).toFixed(2);
                const pctOfTotalPop = (value / totalPop * 100).toFixed(2);
                return `Population: ${formatNum(value)} (${pctOfImmigrants}% of Immigrants, ${pctOfTotalPop}% of Total)`;
              }
            }
          }
        },
        scales: {
          x: {
            min: 0,
            max: chartMax, // Locked scale at exactly 70k to prevent layout jumping
            grid: {
              color: 'rgba(255, 255, 255, 0.05)',
              drawTicks: false
            },
            ticks: {
              callback: function(value) {
                if (value >= 1000) {
                  return (value / 1000) + 'k';
                }
                return value;
              }
            }
          },
          y: {
            grid: { display: false },
            afterFit: function(scaleInstance) {
              scaleInstance.width = 100; // Locked width for country labels to prevent layout jittering
            },
            ticks: {
              font: { weight: 500 }
            }
          }
        }
      },
      plugins: [{
        // Custom Canvas plugin to write actual value text next to every bar
        id: 'barLabels',
        afterDatasetsDraw: function(chart) {
          const ctx = chart.ctx;
          chart.data.datasets.forEach((dataset, i) => {
            const meta = chart.getDatasetMeta(i);
            meta.data.forEach((bar, index) => {
              const activeIdx = parseInt(slider.value, 10);
              const activeQKey = qKeys[activeIdx];
              
              // Resolve actual counts
              const countryData = getTopCountriesData(activeQKey);
              const realVal = countryData.values[index];
              
              // Draw real numeric value text next to the bar
              ctx.fillStyle = '#f8fafc';
              ctx.font = '600 11px Outfit';
              ctx.textAlign = 'left';
              ctx.textBaseline = 'middle';
              const padding = 8;
              const xPos = bar.x + padding;
              const yPos = bar.y;
              ctx.fillText(formatNum(realVal), xPos, yPos);
            });
          });
        }
      }]
    });
  }

  // Update charts when slider value changes
  function updateCharts(qKey) {
    if (!migrationChartInstance || !ancestryChartInstance) return;

    // 1. Update Migration Chart highlight colors
    const immColors = qKeys.map(qk => qk === qKey ? '#10b981' : 'rgba(16, 185, 129, 0.18)');
    const emiColors = qKeys.map(qk => qk === qKey ? '#f97316' : 'rgba(249, 115, 22, 0.18)');

    migrationChartInstance.data.datasets[0].backgroundColor = immColors;
    migrationChartInstance.data.datasets[1].backgroundColor = emiColors;
    migrationChartInstance.update('none');

    // 2. Update Country Chart labels & values (Top 10)
    const countryData = getTopCountriesData(qKey);
    ancestryChartInstance.data.labels = countryData.labels;
    ancestryChartInstance.data.datasets[0].data = countryData.values;
    ancestryChartInstance.update();
  }

  function showError(msg) {
    const mainContainer = document.querySelector(".container");
    mainContainer.innerHTML = `
      <div style="padding: 3rem; text-align: center; background: rgba(239, 68, 68, 0.15); border: 1px solid rgba(239, 68, 68, 0.3); border-radius: 1rem; max-width: 600px; margin: 5rem auto;">
        <h2 style="color: #ef4444; margin-bottom: 1rem;">Configuration Error</h2>
        <p style="color: #cbd5e1; margin-bottom: 2rem;">${msg}</p>
        <div style="background: #0f172a; padding: 1rem; border-radius: 0.5rem; text-align: left; font-family: monospace; font-size: 0.875rem; color: #38bdf8; overflow-x: auto;">
          python prefetch.py
        </div>
      </div>
    `;
  }
});
